version: "3.7"
services:
  react:
    build:
      args:
        - NODE_VER=16.17.1-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/frontend
    ports:
      - 5173:5173
      - 6006:6006
